config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  get :admin_sign_in, to: "admins#sign_in"
  post :admin_log_in, to: "admins#log_in"

  resources :videos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"

  get :sign_up, to: "users#sign_up"
  post :create, to: "users#create"
  get :sign_in, to: "users#sign_in"
  post :log_in, to: "users#log_in"
  get :sign_out, to: "users#sign_out"

  namespace :students do
    get :portal, to: "students#index"

    # quizzes
    get :quizzes, to: "students#quizzes"
    get "quizzes/:id", to: "students#show_quiz", as: :show_quiz
    get "quizzes/:id/attempt", to: "students#attempt_quiz", as: :attempt_quiz
    get "quizzes/:id/attempt/:question_id", to: "students#attemptting_quiz", as: :attemptting_quiz
    post "quizzes/:id/attempt", to: "students#submit_quiz", as: :submit_quiz
    get "submitted", to: "students#submitted"
    get "submitted/:id", to: "students#show_submitted", as: :show_submitted
    get :submitted_quizzes, to: "students#submitted_quizzes"

    # reports
    get :reports, to: "students#reports"
    get "reports/:id", to: "students#show_report", as: :show_report
    get "reports/:id/download", to: "students#download_report", as: :download_report

    # videos
    get :videos, to: "students#videos"
    get "videos/:id", to: "students#show_video", as: :show_video
    get "videos/:id/download", to: "students#download_video", as: :download_video
    get "answer", to: "students#answer"
  end

  namespace :teachers do
    get :portal, to: "teachers#index"

    # students
    get :students, to: "teachers#students"
    get :new_student, to: "teachers#new_student"
    post :add_student, to: "teachers#add_student"
    get "students/:id", to: "teachers#show_student", as: :show_student
    get "students/:id/edit", to: "teachers#edit_student", as: :edit_student
    patch "students/:id", to: "teachers#update_student", as: :update_student
    delete "students/:id", to: "teachers#destroy_student", as: :destroy_student

    # quizzes
    resources :quizzes do
      get :submitted, on: :collection
      get :show_submitted
    end
    post "mark_question/:id", to: "quizzes#mark_question", as: :mark_question
    resources :reports
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/video.rb
class Video < ApplicationRecord
  acts_as_tenant :organization

  has_one_attached :file, dependent: :destroy

  # validate :file_validation

  private

  def file_validation
    if file.attached?
      # Validate file size
      if file.blob.byte_size > 50.megabytes
        errors.add(:file, "size must be less than 50 MB")
      end

      # # Validate file type
      # acceptable_types = ["video/mp4", "video/mkv"]
      # unless acceptable_types.include?(file.blob.content_type)
      #   errors.add(:file, "must be a MP4 or MKV video")
      # end
    else
      errors.add(:file, "must be attached")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    return if params[:video][:question_id].nil?

    student_id = @current_user.id
    @question = Question.find_by(id: params[:video][:question_id])
    @quiz = @question.quiz
    # @quiz.in_progress!

    @video_request = VideoRequest.find_or_create_by(student_id:, question_id: @question.id)
    if params[:video][:live].present?
      @video = Video.find_or_create_by(student_id:, question_id: @question.id)
      @video.file.purge if @video&.file&.attached?
      @video.update(file: params[:video][:live], title: "uploaded")

      answer = Answer.find_or_create_by(student_id:, question_id: @question.id)
      answer.answer = params[:video][:live]
      answer.video_id = @video.id
      answer.is_published = true
      answer.save
    else
      @video = Video.find_by(student_id:, question_id: @question.id)
      @question.answers&.where(student_id:)&.last&.update_column(:is_published, true) if @video&.present?
    end

    # if params[:video][:file].present? # uploaded video
    #   @video = Video.find_or_create_by(student_id:, question_id: @question.id)
    #   @video.update(file: params[:video][:file], title: "uploaded")

    #   answer = Answer.find_or_create_by(student_id:, question_id: @question.id)
    #   answer.answer = params[:video][:answer]
    #   answer.video_id = @video.id
    #   answer.save
    # end
    # if params[:video][:live].present? # live video
    #   @video = Video.find_or_create_by(student_id:, question_id: @question.id)
    #   @video.update(file: params[:video][:live], title: "live")

    #   answer = Answer.find_or_create_by(student_id:, question_id: @question.id)
    #   answer.answer = params[:video][:answer] if params[:video][:answer]
    #   answer.video_id = @video.id if @video.id
    #   answer.save
    # end
    # if params[:video][:file].nil? && params[:video][:live].nil? # text answer
    #   answer = Answer.find_or_create_by(student_id:, question_id: @question.id)
    #   answer.update(answer: params[:video][:answer])
    # end

    respond_to do |format|
      if @video.nil? || @video&.errors&.any? || @video.file&.nil?
        flash[:error] = @video&.errors&.full_messages&.join(", ") || "Please upload a video"
        format.json { render :new, status: :unprocessable_entity }
        format.html { redirect_to students_attemptting_quiz_path(@quiz, @question) }
      else
        format.json { render :show, status: :created, location: @video }
        format.html { redirect_to students_attemptting_quiz_path(@quiz, @question), notice: "Answer was successfully saved." }
      end
      # if @video.save
      #   # format.html { redirect_to @video, notice: "Video was successfully created." }
      # else
      #   # format.html { render :new, status: :unprocessable_entity }
      #   format.json { render json: @video.errors, status: :unprocessable_entity }
      # end
    end

    # if params[:video][:question_id]
    #   Question.find_by(id: params[:video][:question_id]).quiz.update(status: "in_progress")
    # end
    # if params[:video][:file].present? && params[:video][:question_id].present?
    #   @video = Video.create(title: params[:video][:title], file: params[:video][:file])
    #   Answer.create(question_id: params[:video][:question_id], answer: params[:video][:answer], video_id: @video.id)
    #   redirect_to students_submitted_path
    # elsif params[:video][:file].present? && params[:video][:answer].nil?
    #   @video = Video.create(title: params[:video][:title], file: params[:video][:file])
    #   Answer.create(question_id: params[:video][:question_id], answer: params[:video][:answer], video_id: @video&.id)
    #   redirect_to students_submitted_path
    # elsif params[:video][:file].nil? && params[:video][:question_id].present?
    #   Answer.create(question_id: params[:video][:question_id], answer: params[:video][:answer], video_id: Video.last&.id)
    #   redirect_to students_submitted_path
    # else
    #   @video = Video.new(video_params)

    #   respond_to do |format|
    #     if @video.save
    #       format.html { redirect_to @video, notice: "Video was successfully created." }
    #       format.json { render :show, status: :created, location: @video }
    #     else
    #       format.html { render :new, status: :unprocessable_entity }
    #       format.json { render json: @video.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy!

    respond_to do |format|
      format.html { redirect_to videos_path, status: :see_other, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.expect(video: [ :title, :description, :file ])
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.slim
/ = form_with(model: @video, local: false, id: "video-form") do |form|
  = polaris_text_field(form: form, attribute: :title, label: "Video Title", required: true)
  = polaris_text_field(form: form, attribute: :description, label: "Video Description")

  = polaris_stack(distribution: :equal_spacing, alignment: :center, classes: "mt-4") do
    = polaris_button(text: "Start Recording", id: "start", primary: true) { "Start Video" }
    = polaris_button(text: "Stop Recording", id: "stop", destructive: true) { "Stop and Save Video" }

  = tag.video(nil, id: "live", class: "border border-black rounded-md mt-4", width: "300", height: "200", autoplay: true, muted: true)

  = form.hidden_field :file

= polaris_page(title: "New video", back_url: videos_path) do |page|
  = render "shared/flash"
  = form_with(model: Video.new, builder: Polaris::FormBuilder, html: { data: { turbo: true, controller: "form" } } ) do |f|
    / - if video.errors.any?
      div style="color: red"
        h2 = "#{pluralize(video.errors.count, "error")} prohibited this video from being saved:"
        ul
          - video.errors.each do |error|
            li = error.full_message
    = polaris_form_layout(classes: 'mb-3') do |form_layout|
      - form_layout.with_item
        = f.polaris_text_field :title, required: true, placeholder: "Enter title"
      - form_layout.with_item
        = f.hidden_field :file
        = polaris_card(sectioned: true) do
          / = polaris_stack(distribution: :fill) do |stack|
          = polaris_heading(level: 3) { "Record your video" }
          = polaris_stack(wrap: false) do |stack|
            - stack.with_item do
              = tag.video(nil, id: "live", class: "border border-gray-300 rounded-md", width: "300", height: "200", autoplay: true, muted: true)
            - stack.with_item do
              = f.polaris_dropzone :file, as: :video, label: "Upload video", multiple: false, accept: 'video/*'

          = polaris_button(text: "Start Video", id: "start", classes: "mt-2") { "Start Video" }
          = polaris_button(text: "Stop Video", id: "stop", classes: "ml-2", destructive: true) { "Stop and Save Video" }
          / .mt-2
            = tag.video(nil, id: "live", class: "border border-gray-300 rounded-md", width: "300", height: "200", autoplay: true, muted: true)
      / - form_layout.with_item
        = f.polaris_dropzone :file, as: :video, label: "Upload video", multiple: false, accept: 'video/*'
      - form_layout.with_item
        = f.submit "#{params[:action] == 'new' ? 'Submit video' : 'Update video'}", class: "Polaris-Button mr-2 Polaris-Button--primary float-right"
        / = f.submit "Record New Video", class: "Polaris-Button mr-2 Polaris-Button--primary float-right"
        / = polaris_button(text: "Record New Video", url: new_video_path) { "Record New Video" }
        / .my-5.border-t.border-gray-200

app/views/videos/_preview_video.erb
<video controls width="480">
  <source src="<%= rails_blob_url(attachment) %>" type="video/mp4"/>
</video>

app/views/videos/_video.html.slim
div id="#{dom_id video}"
  p
    strong Title: 
    = video.title
  / p
    strong Description:
    = video.description || "N/A"
  / p
    strong Created at:
    = video.created_at
  p
    strong Preview
    = render "preview_video", attachment: video.file
  / p
    strong File:
    = link_to video.file.filename, url_for(video.file)

  / p
    strong Preview:
    iframe src=url_for(video.file) width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen

  .mt-2

app/views/videos/edit.html.slim
h1 Editing video

== render "form", video: @video

br

div
  => link_to "Show this video", @video
  '|
  =< link_to "Back to videos", videos_path

app/views/videos/ex-index.html.slim
p style="color: green" = notice

h1 Videos

#videos
  - @videos.each do |video|
    == render video
    p
      = link_to "Show this video", video

= link_to "New video", new_video_path

app/views/videos/index.html copy.slim
/ = polaris_banner(status: :success, title: notice) if notice

= polaris_page(title: t("Videos")) do |page|
  - page.with_primary_action(url: new_video_path) { "Add new video" }
  = render "shared/flash"
  = polaris_layout do |layout|
    - layout.with_section do
      - @videos.each do |video|
        = render video
        = polaris_horizontal_stack(gap: '1') 
          = polaris_button(icon_name: "ViewIcon", url: video_path(video), primary: true) { "Show video" }
          = polaris_button(icon_name: "EditIcon", url: video_path(video)) { "Edit video" }
          = polaris_button(icon_name: "DeleteIcon", url: video_path(video), destructive: true) { "Delete video" }
        .my-2
          = polaris_divider
      
      - if @videos.empty?
        = render "shared/empty"

      / = polaris_button(text: "New video", url: new_video_path, primary: true, full_width: true, class: "mt-4")

app/views/videos/index.html.slim
= polaris_page(title: "Submissions", subtitle: "List of all submissions", full_width: true) do | polaris_page |
  / - polaris_page.with_custom_primary_action do 
    = polaris_horizontal_stack(gap: '2') do |stack|
      = polaris_button(primary: true, icon_name: "PlusIcon", url: "", data: { turbo_frame: "modal" }) { "Add Student" }

  = polaris_layout do |layout| 
    - layout.with_section do
      = turbo_frame_tag "flash"
        = render "shared/flash"
        | in progress
      / - if @submissions.empty?
        = polaris_card
          = polaris_empty_state( heading: "No student found", image: asset_path("emptystate-files.png")) do |state|
            - state.with_primary_action(url: teachers_new_student_path, data: { turbo_frame: "modal" }) { "Add Student" }
            - state.with_secondary_action(url: "#", data: { turbo_frame: "_top" }) { "Learn more" }
            p Your currentlly have no student.
      / - else
        = polaris_card do |card|
          - card.with_section(unstyled: true)
            = polaris_index_table @submissions.each_with_index do |table, index|
              / - table.with_column "ID" do |row|
                = index.to_i + 1
              - table.with_column "First Name" do |row|
                - link_to teachers_show_student_path(row)
                  b
                    = row.first_name
              - table.with_column "Last Name", classes: "truncate" do |row|
                - link_to teachers_show_student_path(row)
                  b
                    = row.last_name
              - table.with_column "Email" do |row|
                = row.email
              - table.with_column "Status" do |row|
                = row.status.capitalize

              - table.with_column "Action" do |row|
                = polaris_horizontal_stack(gap: '1')  
                  = button_to teachers_show_student_path(row), method: :get do
                    = polaris_icon name: "ViewIcon"
                  = button_to teachers_edit_student_path(row), method: :get, data: { turbo_frame: "modal" } do
                    = polaris_icon name: "EditIcon"
                  = button_to teachers_destroy_student_path(row), method: :delete, data: { turbo: false }, onclick: "return confirm('Are you sure you want to delete this student?')" do
                    = polaris_icon name: "DeleteIcon"
          / - card.with_section(unstyled: true)
            .pagy-container
              == pagy_info(@pagy)
              == pagy_nav(@pagy) 

app/views/videos/new.html.slim
/ h1 New video

== render "form", video: @video

/ br

/ div
/   = link_to "Back to videos", videos_path

app/views/videos/show.html.slim
p style="color: green" = notice

== render @video

div
  => link_to "Edit this video", edit_video_path(@video)
  '|
  =< link_to "Back to videos", videos_path

  = button_to "Destroy this video", @video, method: :delete