config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  get :admin_sign_in, to: "admins#sign_in"
  post :admin_log_in, to: "admins#log_in"

  resources :videos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"

  get :sign_up, to: "users#sign_up"
  post :create, to: "users#create"
  get :sign_in, to: "users#sign_in"
  post :log_in, to: "users#log_in"
  get :sign_out, to: "users#sign_out"

  namespace :students do
    get :portal, to: "students#index"

    # quizzes
    get :quizzes, to: "students#quizzes"
    get "quizzes/:id", to: "students#show_quiz", as: :show_quiz
    get "quizzes/:id/attempt", to: "students#attempt_quiz", as: :attempt_quiz
    get "quizzes/:id/attempt/:question_id", to: "students#attemptting_quiz", as: :attemptting_quiz
    post "quizzes/:id/attempt", to: "students#submit_quiz", as: :submit_quiz
    get "submitted", to: "students#submitted"
    get "submitted/:id", to: "students#show_submitted", as: :show_submitted
    get :submitted_quizzes, to: "students#submitted_quizzes"

    # reports
    get :reports, to: "students#reports"
    get "reports/:id", to: "students#show_report", as: :show_report
    get "reports/:id/download", to: "students#download_report", as: :download_report

    # videos
    get :videos, to: "students#videos"
    get "videos/:id", to: "students#show_video", as: :show_video
    get "videos/:id/download", to: "students#download_video", as: :download_video
    get "answer", to: "students#answer"
  end

  namespace :teachers do
    get :portal, to: "teachers#index"

    # students
    get :students, to: "teachers#students"
    get :new_student, to: "teachers#new_student"
    post :add_student, to: "teachers#add_student"
    get "students/:id", to: "teachers#show_student", as: :show_student
    get "students/:id/edit", to: "teachers#edit_student", as: :edit_student
    patch "students/:id", to: "teachers#update_student", as: :update_student
    delete "students/:id", to: "teachers#destroy_student", as: :destroy_student

    # quizzes
    resources :quizzes do
      get :submitted, on: :collection
      get :show_submitted
    end
    post "mark_question/:id", to: "quizzes#mark_question", as: :mark_question
    resources :reports
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_empty.html.erb
<%= polaris_card do %>
  <%= polaris_empty_state(
    heading: "Manage your videos",
    image: "https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png",
  ) do |state| %>
    <% state.with_primary_action(url: new_video_path) { "Add Video" } %>
    <% state.with_secondary_action(url: "#") { "Learn more" } %>

    <p>Track, manage, and publish your video files.</p>
  <% end %>
<% end %>

app/views/shared/_flash.slim
- flash.each do |type, message|
  - if message.present?
    div class="flash-message flash-#{type}" data-controller="flash" data-action="click->flash#close"
      = message
      button type="button" class="close-button" data-action="flash#close" aria-label="Close"
        span aria-hidden="true" &times;

app/views/shared/_nav.html.erb
<%= polaris_frame(
  logo: {
    url: "/",
    src: "https://cdn.shopify.com/s/files/1/0446/6937/files/jaded-pixel-logo-color.svg",
    width: "124px",
  },
  style: "background-color: white"
) do |frame| %>
  <% frame.with_top_bar do |top_bar| %>
    <% top_bar.with_search_field do |search_field| %>
      <%= polaris_text_field(placeholder: "Search", clear_button: true) %>
    <% end %>
    <%# top_bar.with_secondary_menu do |secondary_menu| %>
      <%# polaris_icon(name: "QuestionCircleIcon") %>
    <%# end %>
    <% top_bar.with_user_menu(name: @current_user.full_name, detail: @current_user.role.titleize) do |user_menu| %>
      <% user_menu.with_avatar(initials: @current_user.first_name[0]) %>
      <%= polaris_action_list do |action_list| %>
        <%# action_list.with_item(icon: "PersonIcon", url: "#") { "Profile" } %>
        <% action_list.with_item(icon: "ExitIcon", url: sign_out_path) { "Log out" } %>
      <% end %>
    <% end %>
  <% end %>
  <% frame.with_navigation do |navigation| %>
    <% navigation.with_section do |section| %>
      <% section.with_item(url: teachers_portal_path, label: "Dashboard", icon: "HomeIcon", selected: is_active_link?(teachers_portal_path, nil)) %>
    <% end %>
    <% navigation.with_section(title: "Education", separator: true) do |section| %>
      <%# section.with_action(icon: "ChatIcon") %>
      <% section.with_item(url: teachers_quizzes_path, label: "Quizzes", icon: "BookIcon", selected: is_active_link?(teachers_quizzes_path)) %>
      <%# section.with_item(url: teachers_reports_path, label: "Reports", icon: "ChartVerticalFilledIcon", selected: is_active_link?(teachers_reports_path, "reports")) %>
      <% section.with_item(url: teachers_students_path, label: "Students", icon: "PersonIcon", selected: is_active_link?(teachers_students_path, nil)) %>
      <%# section.with_item(url: videos_path, label: "Videos", icon: "PlayCircleIcon", selected: is_active_link?(videos_path, "videos")) %>
      <% section.with_item(url: submitted_teachers_quizzes_path, label: "Submissions", icon: "ChartVerticalFilledIcon", selected: is_active_link?(submitted_teachers_quizzes_path, nil)) %>
    <% end %>
    <%# navigation.with_section(separator: true, style:"margin-top:auto; border-top: 1px solid rgba(0,0,0,0.1);") do |section| %>
      <%# section.with_item(url: "#", label: "Notifications", icon: "NotificationIcon", badge: "0" ) %>
      <%# section.with_item(url: "#", label: "Settings", icon: "SettingsIcon") %>
      <%# section.with_item(url: sign_out_path, label: "Log out", icon: "ExitIcon") %>
    <%# end %>
  <% end %>

  <%# render "shared/flash" %>
  <%= yield %>
<% end %>

app/views/shared/_student_nav.erb
<%= polaris_frame(
  logo: {
    url: "/",
    src: "https://cdn.shopify.com/s/files/1/0446/6937/files/jaded-pixel-logo-color.svg",
    width: "124px",
  },
  style: "background-color: white"
) do |frame| %>
  <% frame.with_top_bar do |top_bar| %>
    <% top_bar.with_search_field do |search_field| %>
      <%= polaris_text_field(placeholder: "Search", clear_button: true) %>
    <% end %>
    <%# top_bar.with_secondary_menu do |secondary_menu| %>
      <%# polaris_icon(name: "QuestionCircleIcon") %>
    <%# end %>
    <% top_bar.with_user_menu(name: @current_user.full_name, detail: @current_user.role.titleize) do |user_menu| %>
      <% user_menu.with_avatar(initials: @current_user.first_name[0]) %>
      <%= polaris_action_list do |action_list| %>
        <%# action_list.with_item(icon: "PersonIcon", url: "#") { "Profile" } %>
        <% action_list.with_item(icon: "ExitIcon", url: sign_out_path) { "Log out" } %>
      <% end %>
    <% end %>
  <% end %>
  <% frame.with_navigation do |navigation| %>
    <% navigation.with_section do |section| %>
      <% section.with_item(url: students_portal_path, label: "Dashboard", icon: "HomeIcon", selected: is_active_link?(students_portal_path, nil)) %>
    <% end %>
    <% navigation.with_section(title: "Education", separator: true) do |section| %>
      <%# section.with_action(icon: "ChatIcon") %>
      <% section.with_item(url: students_quizzes_path, label: "Quizzes", icon: "BookIcon", selected: is_active_link?(students_quizzes_path, nil)) %>
      <% section.with_item(url: students_submitted_quizzes_path, label: "Submissions", icon: "ChartVerticalFilledIcon", selected: is_active_link?(students_submitted_quizzes_path, nil)) %>
      <%# section.with_item(url: students_reports_path, label: "Reports", icon: "PersonIcon", selected: is_active_link?(students_reports_path, "reports")) %>
      <%# section.with_item(url: students_videos_path, label: "Videos", icon: "PlayCircleIcon", selected: is_active_link?(students_videos_path, "videos")) %>
    <% end %>
    <%# navigation.with_section(separator: true, style:"margin-top:auto; border-top: 1px solid rgba(0,0,0,0.1);") do |section| %>
      <%# section.with_item(url: "#", label: "Notifications", icon: "NotificationIcon", badge: "0" ) %>
      <%# section.with_item(url: "#", label: "Settings", icon: "SettingsIcon") %>
      <%# section.with_item(url: sign_out_path, label: "Log out", icon: "ExitIcon") %>
    <%# end %>
  <% end %>

  <%# render "shared/flash" %>
  <%= yield %>
<% end %>