config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  get :admin_sign_in, to: "admins#sign_in"
  post :admin_log_in, to: "admins#log_in"

  resources :videos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"

  get :sign_up, to: "users#sign_up"
  post :create, to: "users#create"
  get :sign_in, to: "users#sign_in"
  post :log_in, to: "users#log_in"
  get :sign_out, to: "users#sign_out"

  namespace :students do
    get :portal, to: "students#index"

    # quizzes
    get :quizzes, to: "students#quizzes"
    get "quizzes/:id", to: "students#show_quiz", as: :show_quiz
    get "quizzes/:id/attempt", to: "students#attempt_quiz", as: :attempt_quiz
    get "quizzes/:id/attempt/:question_id", to: "students#attemptting_quiz", as: :attemptting_quiz
    post "quizzes/:id/attempt", to: "students#submit_quiz", as: :submit_quiz
    get "submitted", to: "students#submitted"
    get "submitted/:id", to: "students#show_submitted", as: :show_submitted
    get :submitted_quizzes, to: "students#submitted_quizzes"

    # reports
    get :reports, to: "students#reports"
    get "reports/:id", to: "students#show_report", as: :show_report
    get "reports/:id/download", to: "students#download_report", as: :download_report

    # videos
    get :videos, to: "students#videos"
    get "videos/:id", to: "students#show_video", as: :show_video
    get "videos/:id/download", to: "students#download_video", as: :download_video
    get "answer", to: "students#answer"
  end

  namespace :teachers do
    get :portal, to: "teachers#index"

    # students
    get :students, to: "teachers#students"
    get :new_student, to: "teachers#new_student"
    post :add_student, to: "teachers#add_student"
    get "students/:id", to: "teachers#show_student", as: :show_student
    get "students/:id/edit", to: "teachers#edit_student", as: :edit_student
    patch "students/:id", to: "teachers#update_student", as: :update_student
    delete "students/:id", to: "teachers#destroy_student", as: :destroy_student

    # quizzes
    resources :quizzes do
      get :submitted, on: :collection
      get :show_submitted
    end
    post "mark_question/:id", to: "quizzes#mark_question", as: :mark_question
    resources :reports
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/teachers/quizzes_controller.rb
class Teachers::QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_teacher
  expose :quizzes, -> { Quiz.where(created_by_id: @current_user.id) }
  expose :quiz

  def index
  end

  def edit
    if quiz.started?
      flash[:error] = "This quiz is already started."
    end
  end

  def create
    # quiz.start_time = Time.now
    # quiz.end_time = Time.now
    # start_time = Time.parse("#{quiz_params[:due_date]} #{Time.parse(quiz_params[:start_time]).strftime('%H:%M')}")
    # end_time = Time.parse("#{quiz_params[:due_date]} #{Time.parse(quiz_params[:end_time]).strftime('%H:%M')}")

    # quiz_params[:start_time] = start_time
    # quiz_params[:end_time] = end_time
    quiz.created_by_id = @current_user.id

    if quiz.save
      QuizMailer.quiz_created_email(@current_user, quiz).deliver_now
      respond_to do |format|
        flash[:success] = "Quiz is created successfully."
        format.html { redirect_to teachers_quizzes_path }
      end
    else
      flash[:error] = quiz.errors.full_messages.join(", ")
      # render :new
      redirect_to teachers_quizzes_path
    end
  end

  def update
    if quiz.update(quiz_params)
      respond_to do |format|
        flash[:success] = "Quiz is updated successfully."
        format.html { redirect_to teachers_quizzes_path }
      end
    else
      flash[:error] = quiz.errors.full_messages
      render :edit
    end
  end

  def destroy
    if quiz.destroy
      respond_to do |format|
        flash[:alert] = "Quiz is deleted successfully."
        format.html { redirect_to teachers_quizzes_path }
      end
    end
  end

  def submitted
    @submissions = Submission.joins(:quiz).where(quizzes: { created_by_id: @current_user.id }).where(status: "completed")
    # @submissions = Quiz.where(id: VideoRequest.pluck(:quiz_id))
    # @quizzes = Quiz.where(created_by_id: @current_user.id).joins(:submissions).where(submissions: { status: "completed" })
  end

  def show_submitted
    @quiz = Quiz.find(params[:quiz_id])
    @submission = Submission.find_by(id: params[:submission_id])
  end

  def mark_question
    mark = Mark.find_or_initialize_by(answer_id: params[:id], teacher_id: @current_user.id)
    if mark.update(number: params[:number], comment: params[:comment])
      answer = Answer.find_by(id: params[:id])
      if answer.present?
        student = User.find_by(id: answer.student_id)
        quiz = answer.question.quiz
        test = false
        quiz.questions.each do |q|
          unless Mark.find_by(answer_id: q.answers.where(student_id: student.id, is_published: true).last&.id, teacher_id: @current_user.id)
            test = false
          else
            test = true
          end
        end
        QuizMailer.quiz_marked(student, quiz, "A+").deliver_now if test
      end
      flash[:success] = "Answer marked successfully."
    else
      flash[:error] = "Failed to save the mark. Please try again."
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def quiz_params
    params.require(:quiz).permit(:title, :description, :due_date, :start_time, :end_time, :status, questions_attributes: %i[id title duration description _destroy])
  end
end

app/controllers/teachers/teachers_controller.rb
class Teachers::TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_teacher

  def index
  end

  def students
    @students = User.where(role: "student")
  end

  def new_student
    @student = User.new
  end

  def add_student
    @student = User.new(student_params)
    @student.username = @student.email
    @student.role = "student"
    @student.password = "123456"

    if @student.save
      flash[:success] = "Student created successfully"
    else
      flash[:error] = @student.errors.full_messages.join(", ")
    end
    redirect_to teachers_students_path
  end

  def show_student
    @teacher = User.find(@current_user.id)
    @student = User.find(params[:id])
  end

  def edit_student
    @student = User.find(params[:id])
  end

  def update_student
    @student = User.find(params[:id])

    if @student.update(student_params)
      flash[:success] = "Student updated successfully"
    else
      flash[:error] = @student.errors.full_messages.join(", ")
    end
    redirect_to teachers_students_path
  end

  def destroy_student
    @student = User.find(params[:id])
    if @student.destroy
      flash[:success] = "Student deleted successfully"
      redirect_to teachers_students_path
    end
  end

  private

  def student_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email, :role, :status, :failed_attempts)
  end
end

app/views/teachers/teachers/_student_form.slim
- url = @student.new_record? ? teachers_add_student_path : teachers_update_student_path

= form_with model: @student, url: url, builder: Polaris::FormBuilder, html: { data: { turbo: false, target: "_top", controller: "polaris-modal form", action: "turbo:submit-end->form#closeModal" } } do |f|
  = polaris_modal(title: "#{params[:action].titleize} Student", id: "remote-modal", open: true) do |modal|
    = polaris_layout(classes: "mt-0") do |layout|
      - layout.with_section do
        = polaris_form_layout(classes: 'mb-3') do |form_layout|
          - form_layout.with_group do |group|
            - group.with_item
              = f.polaris_text_field :first_name, required: true, placeholder: "Enter title"
            - group.with_item
              = f.polaris_text_field :last_name, required: true, placeholder: "Enter title"
          - form_layout.with_item
            = f.polaris_text_field :email, label: "Email", required: true, type: :email
          / - form_layout.with_item
          /   = f.polaris_text_field :password, label: "Password", type: :password, required: true, help_text: "Create a strong password with at least 6 characters"
      - modal.with_primary_action(submit: true) { "Save" }
      - modal.with_secondary_action(data: { action: "polaris-modal#close" }) { "Close" }

app/views/teachers/teachers/edit_student.slim
= turbo_frame_tag "modal"
  = render "student_form"

app/views/teachers/teachers/index.slim
= polaris_page(full_width: true) do |page|
  = render "shared/flash"
  / - page.with_primary_action(url: "#" ,"data-turbo-frame": 'modal') { t("Widget") } 

  = polaris_layout do |layout|
    - layout.with_section do
      = polaris_callout_card( illustration: asset_path("dashboar-element.svg")) do |callout|
        = polaris_display_text(size: :medium, style:"font-weight:bold") { "Get Started with Koi Viva Voce" }
        = polaris_spacer(vertical: :extra_tight) 
        = polaris_text_style(variation: :subdued) { "Maximize your educational experience with our step-by-step guidance for a seamless setup Get up and running in no time. Discover the power of Koi Viva Voce today!" }

      / = polaris_card() do |card|
        - card.with_section(sectioned: true) do
          = polaris_stack(alignment: :center) do |stack|
            - stack.with_item() do
              = polaris_icon(name: "BookIcon", backdrop: true)
            - stack.with_item(fill: true) do 
              = polaris_heading() { "Schedule an onboarding session" }
            - stack.with_item() do  
              - name = "CircleTickMajor"
              - variant = :success
              = polaris_icon(name: name, color: variant)
            - stack.with_item() do
              = polaris_button(plain: true, data: {controller: "polaris", target:"#onbaording", action:"polaris#toggleCollapsible"}) do |button|
                / - polaris_icon(name: "BookIcon", backdrop: true)
                - button.with_icon(name: "ChevronDownIcon") { "Learn more" }
          = polaris_collapsible(id: "onbaording", open: true) do
            = polaris_spacer(vertical: :loose) 
            hr
            = polaris_spacer(vertical: :loose) 
            = polaris_callout_card(title: "Streamline your Koi Viva Voce journey with a personalized onboarding session Get started efficiently and make the most of your experience", variation: :subdued,  illustration: asset_path("logo.jpg"), style:"box-shadow:none !important;padding-bottom:0px;") do |callout|
              - callout.with_primary_action(url: "mailto:m.test@gmail.com", primary: true) { "Schedule a session" }
              / - callout.with_secondary_action(url: "#", secondary: true) { "Mark as completed" }
      = polaris_card(title: "Quiz Creation Summary") do |card|
        = line_chart Quiz.group_by_day(:created_at).count, name: "Quizzes", height: "350px", options: {series: {smooth: true},toolbox: {feature: {saveAsImage: { show: true }}}}
        / - card.with_section(title: "Quick Stats | Quiz Summary") do

      = polaris_card(title: "Quiz Submissions") do |card|
        = bar_chart Submission.group_by_day(:created_at).count, name: "Submissions", height: "350px", options: {series: {smooth: true},toolbox: {feature: {saveAsImage: { show: true }}}}

app/views/teachers/teachers/new_student.slim
= turbo_frame_tag "modal"
  = render "student_form"

app/views/teachers/teachers/show_student.slim
ruby:
  quizzes = Quiz.where(created_by_id: @teacher.id)
  secondary_actions = []
  secondary_actions << {content: "Delete", url: teachers_destroy_student_path(@student), icon_name: "DeleteIcon", destructive: true, method: :delete, data: { method: :delete, turbo: false, confirm: "Are you sure you want to delete this student?" }}

= polaris_page(title: "Individual Student Report", subtitle: "Detailed Report of #{@student.full_name}", back_url: teachers_students_path) do |page|
  / - page.with_title_metadata do
    = polaris_badge(status: :success) { @student.status }
  - page.with_primary_action(url: teachers_edit_student_path(@student), icon_name: "EditIcon", data: { turbo_frame: "modal" }) { "Edit" }
  = polaris_card(title: @student.full_name) do |card|
    - card.with_section(border_bottom: true) do
      p <b>Email:</b> #{@student.email}
      p <b>Status:</b> #{@student.status}
    - card.with_section(title: "Quizzes") do
      - quizzes.each_with_index do |quiz, index|
        b #{index.to_i + 1}: #{quiz.title}
        br
        p <b>Description:</b> #{quiz.description}
        p <b>Status:</b> #{quiz.is_submitted?(@student.id) ? "Submitted" : "Not Submitted"} | <b>Due Date:</b> #{quiz.due_date&.strftime("%B %d, %Y")}
        p <b>Total Questions:</b> #{quiz.questions.count}
        - if quiz.is_submitted?(@student.id)
          p <b>Score:</b> #{quiz.score(@student.id)}
        br
    / p
      = link_to "Back to quizzes", teachers_students_path

app/views/teachers/teachers/students.slim
= polaris_page(title: "Students", subtitle: "List of all students", full_width: true) do | polaris_page |
  - polaris_page.with_custom_primary_action do 
    = polaris_horizontal_stack(gap: '2') do |stack|
      = polaris_button(primary: true, icon_name: "PlusIcon", url: teachers_new_student_path, data: { turbo_frame: "modal" }) { "Add Student" }

  = polaris_layout do |layout| 
    - layout.with_section do
      = turbo_frame_tag "flash"
        = render "shared/flash"
      - if @students.empty?
        = polaris_card
          = polaris_empty_state( heading: "No student found", image: asset_path("emptystate-files.png")) do |state|
            - state.with_primary_action(url: teachers_new_student_path, data: { turbo_frame: "modal" }) { "Add Student" }
            - state.with_secondary_action(url: "#", data: { turbo_frame: "_top" }) { "Learn more" }
            p Your currentlly have no student.
      - else
        = polaris_card do |card|
          - card.with_section(unstyled: true)
            = polaris_index_table @students.each_with_index do |table, index|
              / - table.with_column "ID" do |row|
                = index.to_i + 1
              - table.with_column "First Name" do |row|
                - link_to teachers_show_student_path(row)
                  b
                    = row.first_name
              - table.with_column "Last Name", classes: "truncate" do |row|
                - link_to teachers_show_student_path(row)
                  b
                    = row.last_name
              - table.with_column "Email" do |row|
                = row.email
              - table.with_column "Status" do |row|
                = row.status.capitalize

              - table.with_column "Action" do |row|
                = polaris_horizontal_stack(gap: '1')  
                  = button_to teachers_show_student_path(row), method: :get do
                    = polaris_icon name: "ViewIcon"
                  = button_to teachers_edit_student_path(row), method: :get, data: { turbo_frame: "modal" } do
                    = polaris_icon name: "EditIcon"
                  = button_to teachers_destroy_student_path(row), method: :delete, data: { turbo: false }, onclick: "return confirm('Are you sure you want to delete this student?')" do
                    = polaris_icon name: "DeleteIcon"
          / - card.with_section(unstyled: true)
            .pagy-container
              == pagy_info(@pagy)
              == pagy_nav(@pagy) 