config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  get :admin_sign_in, to: "admins#sign_in"
  post :admin_log_in, to: "admins#log_in"

  resources :videos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"

  get :sign_up, to: "users#sign_up"
  post :create, to: "users#create"
  get :sign_in, to: "users#sign_in"
  post :log_in, to: "users#log_in"
  get :sign_out, to: "users#sign_out"

  namespace :students do
    get :portal, to: "students#index"

    # quizzes
    get :quizzes, to: "students#quizzes"
    get "quizzes/:id", to: "students#show_quiz", as: :show_quiz
    get "quizzes/:id/attempt", to: "students#attempt_quiz", as: :attempt_quiz
    get "quizzes/:id/attempt/:question_id", to: "students#attemptting_quiz", as: :attemptting_quiz
    post "quizzes/:id/attempt", to: "students#submit_quiz", as: :submit_quiz
    get "submitted", to: "students#submitted"
    get "submitted/:id", to: "students#show_submitted", as: :show_submitted
    get :submitted_quizzes, to: "students#submitted_quizzes"

    # reports
    get :reports, to: "students#reports"
    get "reports/:id", to: "students#show_report", as: :show_report
    get "reports/:id/download", to: "students#download_report", as: :download_report

    # videos
    get :videos, to: "students#videos"
    get "videos/:id", to: "students#show_video", as: :show_video
    get "videos/:id/download", to: "students#download_video", as: :download_video
    get "answer", to: "students#answer"
  end

  namespace :teachers do
    get :portal, to: "teachers#index"

    # students
    get :students, to: "teachers#students"
    get :new_student, to: "teachers#new_student"
    post :add_student, to: "teachers#add_student"
    get "students/:id", to: "teachers#show_student", as: :show_student
    get "students/:id/edit", to: "teachers#edit_student", as: :edit_student
    patch "students/:id", to: "teachers#update_student", as: :update_student
    delete "students/:id", to: "teachers#destroy_student", as: :destroy_student

    # quizzes
    resources :quizzes do
      get :submitted, on: :collection
      get :show_submitted
    end
    post "mark_question/:id", to: "quizzes#mark_question", as: :mark_question
    resources :reports
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/students/students_controller.rb
class Students::StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_student
  before_action :quiz_submitted?, only: %i[attemptting_quiz attempt_quiz]

  def index
  end

  def quizzes
    @quizzes = Quiz.all
  end

  def show_quiz
    @quiz = Quiz.find(params[:id])
  end

  def attempt_quiz
    @quiz = Quiz.find(params[:id])
    @quiz.update_column(:started, true)

    if params[:start].present? && VideoRequest.find_by(student_id: @current_user.id, quiz_id: @quiz.id).present?
      flash[:error] = "You have already tried to submit this quiz"
      redirect_to students_quizzes_path
      return
    end
    @video_request = VideoRequest.find_or_create_by(student_id: @current_user.id, quiz_id: @quiz.id)
  end

  def submit_quiz
    @quiz = Quiz.find(params[:id])

    if @quiz.update(quiz_params)
      flash[:success] = "Quiz submitted successfully."
      QuizMailer.quiz_submitted(@quiz.created_by, @current_user, @quiz).deliver_now
      redirect_to students_quizzes_path
    end
  end

  def submitted_quizzes
    if params[:id].present?
      Submission.create(user_id: @current_user.id, status: "completed", quiz_id: params[:id])
      flash[:success] = "Quiz submitted successfully."
    end
    # @quizzes = Quiz.where(status: "completed")
    # @quizzes = Quiz.joins(:submissions).where(submissions: { status: "completed", user_id: @current_user.id })
    @quizzes = Quiz.where(id: VideoRequest.where(student_id: @current_user.id).pluck(:quiz_id))
    # @quizzes = Quiz.where(id: VideoRequest.where(student_id: @current_user.id).where.not(quiz_id
    # @quizzes = Quiz.where(status: "submitted", user_id: @current_user.id)
  end

  def reports
    @reports = Report.all
  end

  def videos
    @videos = Video.all
  end

  def show_report
    @report = Report.find(params[:id])
  end

  def show_video
    @video = Video.find(params[:id])
  end

  def download_video
    @video = Video.find(params[:id])
    send_file @video.file.path, type: @video.file.content_type
  end

  def download_report
    @report = Report.find(params[:id])
    send_file @report.file.path, type: @report.file.content_type
  end

  def submitted
    if params[:id].present?
      @quiz = Quiz.find(params[:id])
      # @quiz.pending!

      q_count = @quiz.questions.count
      v_count = 0
      @quiz.questions.each do |question|
        v_count += 1 if VideoRequest.find_by(student_id: @current_user.id, question_id: question.id)
      end
      unless q_count.eql?(v_count)
        flash[:error] = "Please attempt all the questions before submitting."
        redirect_to students_attemptting_quiz_path(@quiz, @quiz.questions&.last)
        return
      end
      @quiz.submissions.create(user_id: @current_user.id, status: "completed") unless @quiz.is_submitted?(@current_user.id)
      flash[:success] = "Quiz submitted successfully."
    else
      flash[:error] = "Please select a quiz to submit."
    end

    respond_to do |format|
      format.html
    end

    # respond_to do |format|
    #   format.html { redirect_to students_submitted_quizzes_path }
    # end
  end

  def attemptting_quiz
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    @question = @quiz.questions.find_by(id: params[:question_id])
  end

  def show_submitted
    @quiz = Quiz.find(params[:id])
  end

  private

  def quiz_submitted?
    if params[:id].present? && Quiz.find(params[:id]).is_submitted?(@current_user.id)
      flash[:error] = "You have already submitted this quiz"
      redirect_to students_submitted_quizzes_path
    end
    # elsif VideoRequest.find_by(student_id: @current_user.id, quiz_id: params[:id]).present?
    #   flash[:error] = "You have already tried to submit this quiz"
    #   redirect_to students_quizzes_path

    if params[:id].present?
      if Quiz.find(params[:id]).due_date == Date.today
        time = Time.parse(Quiz.find(params[:id]).end_time.to_s)
        quiz_hour = time.hour
        quiz_minute = time.min

        # time = Time.current
        time = Time.now
        hour = time.hour
        minute = time.min
        if hour > quiz_hour || (hour == quiz_hour && minute > quiz_minute)
          flash[:error] = "You have missed the deadline for this quiz"
          redirect_to students_quizzes_path
        end
      elsif Quiz.find(params[:id]).due_date < Date.today
        flash[:error] = "You have missed the deadline for this quiz"
        redirect_to students_quizzes_path
      end
    end
  end
end

app/views/students/students/_answer_section copy.slim
/ - card.with_section do
  = polaris_text_container do
    = question.title

- if question.present?
  = form_with(model: Video.new, builder: Polaris::FormBuilder, html: { data: { turbo: false, controller: "form" } } ) do |f|
    / = f.submit "Save Answer", class: "Polaris-Button mr-2 Polaris-Button--primary float-right"
    = polaris_form_layout(classes: 'mb-3') do |form_layout|
      - form_layout.with_group do |group|
        - group.with_item
          = f.hidden_field :question_id, value: question.id
          = f.polaris_text_field :answer, label_hidden: true, value: question&.answers&.where(student_id: @current_user.id)&.last&.answer, multiline: true, rows: 7, placeholder: "Enter your answer here"
        - group.with_item
          = f.polaris_dropzone :file, as: :video, label: "Upload video", multiple: false, accept: 'video/*'
          / - url = cloudinary_url(question&.answers&.last&.video&.file&.blob&.key, resource_type: 'content_type: "video/quicktime"', format: "mov")
          / - url = cloudinary_url_for(question&.answers&.last&.video&.file&.blob)
          / - url = cloudinary_url(question&.answers&.where(student_id: @current_user.id)&.last&.video&.file&.blob&.key, resource_type: 'raw', format: "mp4") if question&.answers&.last&.video&.title.eql?("live")
          / - url = cloudinary_url(question&.answers&.where(student_id: @current_user.id)&.last&.video&.file&.blob&.key, resource_type: 'video', format: "mov") unless question&.answers&.last&.video&.title.eql?("live")
          - if question&.answers&.where(student_id: @current_user.id)&.last&.video&.file&.attached?
            = polaris_link(url: url_for(question&.answers&.where(student_id: @current_user.id)&.last&.video&.file), target: "_blank") { "View Video" }
          / | #{question&.answers&.last&.video&.file&.url}
      / - form_layout.with_item
        br
        / = binding.pry
        / = video_tag question&.answers&.last&.video&.file&.url
        = link_to 'Link Text', url, html_options = {target: '_blank'}
        / = link_to 'Watch Video', question&.answers&.last&.video&.file&.url, class: 'btn btn-primary', target: '_blank', rel: 'noopener'
        / = polaris_button(url: question&.answers&.last&.video&.file&.url, text: "View Video", classes: "mb-1", style: "background-color: #51c35d; font-weight: bold; color: white") { "View Video" }

    - card.with_section(title: "Question: #{question&.title || "Question"}", subdued: true) do
      = polaris_text_container do
        = question&.description || "Question description"

    - card.with_section(title: "Solve the question", "x-data" => "{ open: false }") do
      = polaris_button(text: "Toggle Video Options", classes: "mb-1", "@click" => "open = !open", style: "background-color: #51c35d; font-weight: bold; color: white") { "Record New Video" }
      div x-show="open"
        / = polaris_heading(level: 3) { "Record your video" }
        / = polaris_spacer(vertical: :tight)
        = polaris_stack(wrap: false) do |stack|
          - stack.with_item do
            = tag.video(nil, id: "live", class: "border border-gray-300 rounded-md", width: "300", height: "200", autoplay: true, muted: true)
          / - stack.with_item do
            = f.polaris_dropzone :file, as: :video, label: "Upload video", multiple: false, accept: 'video/*'

        #video-recording-seconds
        = polaris_button(text: "Start Video", id: "start", classes: "mt-2") { "Start Video" }
        = polaris_button(text: "Stop Video", id: "stop", classes: "ml-2", destructive: true) { "Stop and Save Video" }
    / = f.submit "#{params[:action] == 'new' ? 'Submit video' : 'Update video'}", class: "Polaris-Button mr-2 Polaris-Button--primary float-right"
    = f.submit "Save Answer", class: "Polaris-Button mr-2 Polaris-Button--primary"
    .mt-12
    / - card.with_primary_footer_action(type: "submit", icon_name: "ArrowRightIcon") { "Next Question" }
  / - card.with_section(title: "Note") do
    = polaris_text_container do
      | The sales reports are available only if your store is on the Shopify plan
      | or higher.

  / - card.with_primary_footer_action(url: "#", icon_name: "CheckIcon") { "Submit" }
  / - card.with_primary_footer_action(url: "#", icon_name: "ArrowRightIcon") { "Next Question" }
  / - card.with_secondary_footer_action(url: "#", icon_name: "ArrowLeftIcon") { "Previous Question" }
  / - card.with_secondary_footer_action(url: "#", icon_name: "BackspaceIcon") { "Dismiss" }
- else
  = polaris_empty_state( heading: "No question is available yet", image: asset_path("emptystate-files.png")) do |state|
    / - state.with_primary_action(url: new_teachers_quiz_path, data: { turbo_frame: "modal" }) { "Add Quiz" }
    / - state.with_secondary_action(url: "#", data: { turbo_frame: "_top" }) { "Learn more" }
    p There's no question generated yet. Try connecting to your teacher.

app/views/students/students/_answer_section.slim
- if question.present?
  = form_with(model: Video.new, builder: Polaris::FormBuilder, html: { data: { turbo: false, controller: "form" } }) do |f|
    = polaris_form_layout(classes: 'mb-3') do |form_layout|
      - form_layout.with_group do |group|
        - group.with_item
          = f.hidden_field :question_id, value: question.id
          = f.hidden_field :duration, value: question.duration, id: "duration"
          / = f.hidden_field :live, as: :video, id: "live-input"
        - group.with_item
          = f.polaris_dropzone :live, as: :video, label: "Upload video", multiple: false, accept: 'video/*', hidden: true, id: "live-input"
          / - answer = question&.answers&.where(student_id: @current_user.id, is_published: true)&.last
          / - if answer&.present?
          /   = f.hidden_field :answer, value: answer&.id, id: "answer-input"
          - video_request = VideoRequest.find_by(student_id: @current_user.id, question_id: question.id)
          - if video_request&.present?
            = f.hidden_field :answer, value: video_request&.id, id: "answer-input"

      - card.with_section(title: "Question #{question&.number}: #{question&.title || "Question"}", subdued: true) do
        = polaris_text_container do
          | description: #{question&.description || "Question description"}
          br
          | duration: #{question&.duration || 0} minutes
      - card.with_section
        center
          #prefix
          div id="preview" style="display:none; margin-top: 1rem;"
            = tag.video(nil, controls: true, width: "640", height: "360", preload: "metadata", src: url_for(question&.answers&.where(student_id: @current_user.id)&.last&.video&.file))
      #answer
        - card.with_section(title: "Answer:", id: "answer") do
          div class="grid grid-cols-2 gap-4"
            div
              = tag.video(nil, id: "live", class: "border border-gray-300 rounded-md", width: "300", height: "200", autoplay: true, muted: true)

              #video-recording-seconds
              #auto-recording
                = polaris_button(text: "Start Video", id: "auto-start", classes: "mt-2", hidden: true) { "Start Video" }
              = polaris_button(text: "Start Video", id: "start", classes: "mt-2") { "Re Record Video" }
              = polaris_button(text: "Stop Video", id: "stop", classes: "mt-2", destructive: true) { "Stop and Preview" }
              / div id="submit"
                = f.submit "Save Answer", class: "Polaris-Button mr-2 Polaris-Button--primary mt-2"
            div
              #recorded
              / | Preview
            / - card.with_section(title: "Preview:", id: "preview") do
    = f.submit "Save Answer", class: "Polaris-Button mr-2 Polaris-Button--primary", id: "submit"
- else
  = polaris_empty_state(heading: "No question is available yet", image: asset_path("emptystate-files.png")) do |state|
    p There's no question generated yet. Try connecting to your teacher.

app/views/students/students/attempt_quiz.slim
ruby:
  quiz = @quiz
  question = @quiz.questions&.first

= polaris_page(title: quiz.title, back_url: students_quizzes_path, subtitle: quiz.description.truncate(75), full_width: true) do |page|
  - page.with_title_metadata do
    = polaris_badge(status: :success) { "In Progress" }
  / - page.with_primary_action(url: students_submitted_path(id: quiz.id), icon_name: "CheckIcon", data: { turbo: false }) { "Submit" }

  / - title = quiz.questions.any? ? "Status: 1/#{quiz.questions.count}" : "Status: 0/0"
  - title = ""
  = render "shared/flash"
  = polaris_card(title: title) do |card|
    / - card.with_section(border_bottom: true)
      p.overflow-auto#question-time
        | Total time: #{quiz.total_time} minutes | Question time: #{question&.duration || 0} minutes
    - if question
      = turbo_frame_tag "answer_section"
        = render "answer_section", question: question, quiz: quiz, card: card

      - card.with_primary_footer_action(url: students_submitted_path(id: quiz.id), icon_name: "CheckIcon", data: { turbo: false, confirm: "Are you sure that you want to submit this quiz?" }) { "Submit" } if question&.is_last?
      - card.with_primary_footer_action(url: students_attemptting_quiz_path(quiz, question&.next_question), icon_name: "ArrowRightIcon") { "Next Question" } unless question&.is_last?
      - card.with_secondary_footer_action(url: students_attemptting_quiz_path(quiz, question&.previous_question), icon_name: "ArrowLeftIcon") { "Previous Question" } unless question&.is_first?
      / - card.with_secondary_footer_action(url: "#", icon_name: "BackspaceIcon") { "Dismiss" }

app/views/students/students/quizzes.slim
= polaris_page(title: "Quizzes", subtitle: "List of all quizzes", full_width: true) do | polaris_page |
  - polaris_page.with_custom_primary_action do
  - polaris_page.with_custom_primary_action do 
    / = polaris_horizontal_stack(gap: '2') do |stack|
      = polaris_button(primary: true, icon_name: "PlusIcon", url: new_teachers_quiz_path, data: { turbo_frame: "modal" }) { "Add Quiz" }
      / = polaris_button(primary: true, icon_name: "PlusIcon", url: new_teachers_quiz_path, data: { turbo: true, turbo_frame: :modal } ) { "Add Quiz" }

  = polaris_layout do |layout|
  = polaris_layout do |layout| 
    - layout.with_section do
      = turbo_frame_tag "flash"
        = render "shared/flash"
      - if @quizzes.empty?
        = polaris_card
          = polaris_empty_state( heading: "No quiz generated yet", image: asset_path("emptystate-files.png")) do |state|
            / - state.with_primary_action(url: new_teachers_quiz_path, data: { turbo_frame: "modal" }) { "Add Quiz" }
            / - state.with_secondary_action(url: "#", data: { turbo_frame: "_top" }) { "Learn more" }
            p There's no quiz generated yet. Try connecting to your teacher.
      - else
        = polaris_card do |card|
          - card.with_section(unstyled: true)
            = polaris_index_table @quizzes.each_with_index do |table, index|
              / - table.with_column "ID" do |row|
                = index.to_i + 1
              - table.with_column "Title" do |row|
                - link_to students_show_quiz_path(row)
                  b
                    = row.title
              - table.with_column "Description", classes: "truncate" do |row|
                = row.description
              - table.with_column "Status" do |row|
                = row.submissions_status(@current_user.id)
              - table.with_column "Due Date" do |row|
                = row.due_date
              - table.with_column "Start Time" do |row|
                = row.start_time.strftime("%H:%M")
              - table.with_column "End Time" do |row|
                = row.end_time.strftime("%H:%M")
              - table.with_column "Questions" do |row|
                = row.questions.count || 0 

              - table.with_column "Action" do |row|
                = polaris_horizontal_stack(gap: '1')  
                  = polaris_link(url: students_show_quiz_path(row), method: :get, title: "View Quiz") do
                    = polaris_icon name: "ViewIcon"
                  / = button_to students_show_quiz_path(row), method: :get } do
                    = polaris_icon name: "ViewIcon"
                  - video_request = VideoRequest.find_by(student_id: @current_user.id, quiz_id: row.id)
                  - unless row.is_submitted?(@current_user.id)# || video_request.present?
                    = polaris_link(url: students_attempt_quiz_path(row), method: :get, params: { start: true }, title: "Attempt Quiz") do
                      = polaris_icon name: "BookIcon"
                    / = button_to students_attempt_quiz_path(row), method: :get, params: { start: true } do
                      = polaris_icon name: "BookIcon"
                  / = button_to teachers_quiz_path(row), method: :delete, data: { turbo: false }, onclick: "return confirm('Are you sure you want to delete this quiz?')" do
                    = polaris_icon name: "DeleteIcon"
          / - card.with_section(unstyled: true)
            .pagy-container
              == pagy_info(@pagy)
              == pagy_nav(@pagy) 

app/views/students/students/show_quiz.slim
ruby:
  quiz = @quiz
  secondary_actions = []
  secondary_actions << {content: "Delete", url: teachers_quiz_path(quiz), icon_name: "DeleteIcon", destructive: true, method: :delete, data: { method: :delete, turbo: false, confirm: "Are you sure you want to delete this quiz?" }}

= polaris_page(title: quiz.title, subtitle: quiz.description.truncate(75), back_url: students_quizzes_path) do |page|
  - page.with_title_metadata do
    = polaris_badge(status: :success) { quiz.status }
  - unless quiz.is_submitted?(@current_user.id)
    - page.with_primary_action(url: students_attempt_quiz_path(quiz, start: true), icon_name: "BookIcon") { "Attempt Quiz" }
  = polaris_card(title: quiz.title) do
    p.overflow-auto
      | #{quiz.description}
    p
      | #{quiz.due_date&.strftime("%B %d, %Y")}
    p
      | #{quiz.questions.count} questions
    / p
      = link_to "Back to quizzes", teachers_quizzes_path

app/views/students/students/show_submitted.slim
- student_id = @current_user.id

= polaris_page(title: @quiz.title, back_url: students_submitted_quizzes_path, subtitle: @quiz.description.truncate(75), full_width: true) do |page|
  - page.with_title_metadata do
    = polaris_badge(status: :success) { "Completed" }
  
  / - page.with_secondary_action(url: students_quizzes_path, icon_name: "ArrowLeftIcon") { "Back to Quizzes" }

  = render "shared/flash"

  = polaris_card(title: "Quiz Summary") do |card|
    - card.with_section(border_bottom: true) do
      p Total Questions: #{@quiz.questions.count}
      / p "Time Taken: #{@quiz.time_taken} minutes"

    - card.with_section(title: "Student Answers") do
      = polaris_stack(wrap: false, vertical: true) do |stack|
        - @quiz.questions.each_with_index do |question, index|
          - stack.with_item do
            = polaris_card(title: "Question #{index + 1}: #{question.title}", subdued: true) do |question_card|
              - question_card.with_section(border_bottom: true) do
                / p "Question Description:"
                p.question-description= question.description
              
              - question_card.with_section(title: "Your Answer", subdued: true) do
                / p.answer= question.answers.last&.answer || "No answer submitted."
                / - if question.answers.last&.answer
                /   = question.answers.last&.answer
                / - else
                /   | No answer submitted.
                .mt-1
                - if question.answers.last&.video&.file&.attached?
                  / - url = cloudinary_url(question&.answers&.last&.video&.file&.blob&.key, resource_type: 'raw', format: "mp4") if question&.answers&.last&.video&.title.eql?("live")
                  / - url = cloudinary_url(question&.answers&.last&.video&.file&.blob&.key, resource_type: 'video', format: "mov") unless question&.answers&.last&.video&.title.eql?("live")
                  / h1 Video Submission:
                  = tag.video(nil, controls: true, width: "640", height: "360", preload: "metadata", src: url_for(question&.answers&.last&.video&.file))
                  / = link_to "Submitted Video", cloudinary_url(question.answers.last.video.file.key, resource_type: 'video', format: "mp4"), target: "_blank", rel: "noopener"
                - else
                  | No Answer submission.
              - if question.answers&.where(student_id:)&.last&.answer
                - if question.answers&.where(student_id:)&.last&.mark
                  - question_card.with_section(title: "Question Rating", subdued: true) do
                    = "Rating: #{question.answers&.where(student_id:)&.last&.mark&.number} / 10"
                    br
                    = "Comment: #{question.answers&.where(student_id:)&.last&.mark&.comment.present? ? question.answers&.where(student_id:)&.last&.mark&.comment : "N/A"}"
                  / = form_with url: teachers_mark_question_path(question.answers&.last) do |f|
                  / = form_with url: teachers_mark_question_path(question.answers&.where(student_id: @submission.user_id)&.last), builder: Polaris::FormBuilder, html: { data: { turbo: false, target: "_top", controller: "polaris-modal form", action: "turbo:submit-end->form#closeModal" } } do |f|
                    = polaris_form_layout do |form_layout|
                      - form_layout.with_group do |group|
                        - group.with_item
                          = f.polaris_select(:number, label: "Rating", selected: question.answers&.where(student_id: @submission.user_id)&.last&.mark&.number, select_options: { prompt: "Select rating" }, options: (1..10).map { |num| [num, num.to_s] }, required: true)
                        - group.with_item
                          = f.polaris_text_field :comment, multiline: true, value: question.answers&.where(student_id: @submission.user_id)&.last&.mark&.comment, rows: 1, placeholder: "comment here if any"
                        - group.with_item
                          = f.submit "Save Mark", class: "Polaris-Button Polaris-Button--primary mt-5"
                - else
                  - question_card.with_section(title: "Question Rating", subdued: true) do
                    | No rating yet.

              / - question_card.with_section(title: "Correct Answer", subdued: true) do
                p.correct-answer= "No correct answer provided."
  
  - unless Submission.find_by(user_id: @current_user.id, quiz_id: @quiz.id).present?
    - page.with_primary_action(url: students_submitted_quizzes_path(id: @quiz.id), icon_name: "CheckCircleIcon") { "Submit Quiz Now" }

app/views/students/students/submitted.slim
= polaris_page(title: "#{@quiz.title || "Quizz"}", subtitle: "Congratulations! your quiz has been submitted") do | polaris_page |
  - polaris_page.with_custom_primary_action do 
    = polaris_horizontal_stack(gap: '2') do |stack|
      = polaris_button(primary: true, icon_name: "HomeIcon", url: students_quizzes_path) { "View Quizzes" }
  = polaris_layout do |layout| 
    - layout.with_section do
      = render "shared/flash"

    - layout.with_section do
      | #{@current_user.full_name}, your quizz has been submitted. Thank you!

app/views/students/students/submitted_quizzes.slim
= polaris_page(title: "Submitted Quizzes", subtitle: "List of all submitted quizzes") do | polaris_page |
  - polaris_page.with_custom_primary_action do 
    / = polaris_horizontal_stack(gap: '2') do |stack|
      = polaris_button(primary: true, icon_name: "PlusIcon", url: new_teachers_quiz_path, data: { turbo_frame: "modal" }) { "Add Quiz" }
      / = polaris_button(primary: true, icon_name: "PlusIcon", url: new_teachers_quiz_path, data: { turbo: true, turbo_frame: :modal } ) { "Add Quiz" }

  = polaris_layout do |layout| 
    - layout.with_section do
      = turbo_frame_tag "flash"
        = render "shared/flash"
      - if @quizzes.empty?
        = polaris_card
          = polaris_empty_state( heading: "No quiz submitted yet", image: asset_path("emptystate-files.png")) do |state|
            / - state.with_primary_action(url: new_teachers_quiz_path, data: { turbo_frame: "modal" }) { "Add Quiz" }
            / - state.with_secondary_action(url: "#", data: { turbo_frame: "_top" }) { "Learn more" }
            p There's no quiz submitted yet.
      - else
        = polaris_card do |card|
          - card.with_section(unstyled: true)
            = polaris_index_table @quizzes.each_with_index do |table, index|
              / - table.with_column "ID" do |row|
                = index.to_i + 1
              - table.with_column "Title" do |row|
                - link_to students_show_submitted_path(row)
                  b = row.title

                  - flag = row&.questions.any? { |question| question.answers&.last&.mark.present? }
                  - if flag
                    = polaris_badge(status: :info, style: "margin-left: 10px") { "Marked" }

              - table.with_column "Description", classes: "truncate" do |row|
                = row.description
              - table.with_column "Status" do |row|
                | Submitted
              - table.with_column "Due Date" do |row|
                = row.due_date
              - table.with_column "Start Time" do |row|
                = row.start_time.strftime("%H:%M")
              - table.with_column "End Time" do |row|
                = row.end_time.strftime("%H:%M")
              - table.with_column "Questions" do |row|
                = row.questions.count || 0 

          / - card.with_section(unstyled: true)
            .pagy-container
              == pagy_info(@pagy)
              == pagy_nav(@pagy) 